//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sprint.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationState
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> FK_CurrentRacer { get; set; }
        public Nullable<System.Guid> FK_CurrentCarClass { get; set; }
        public Nullable<int> CurrentRaceNumber { get; set; }
    
        public virtual Racer CurrentRacer { get; set; }
        public virtual CarClass CarClass { get; set; }
    }
}
