//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sprint.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RacesOption
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> Id_CarClass { get; set; }
        public int RaceCount { get; set; }
        public int LidersCount { get; set; }
    
        public virtual CarClass CarClass { get; set; }
    }
}
